### ISSUE TITLE
Opening issue of my private repository in safari shows 404

### ISSUE THREAD

**Issue by funkenstrahlen** [cocreation/gitshot#12]
<hr /><div align="center"><img alt="Screenshot uploaded with GitShot" src="https://i.imgur.com/875RemM.png" width="300.0" height="533.6" align="center" /><br><br>Documented with <a href="https://goo.gl/oZUi2a">GitShot</a></div><hr />

**Comment by jeanfw** [comment]
Hello @funkenstrahlen, thanks for all your feedback!
Regarding this specific issue, unfortunately GitHub doesn’t allow us to automatically open a session in our in-app Safari and cookies aren’t shared from the rest of the system: have you tried signing in to your GitHub account in this window ?

**Comment by funkenstrahlen** [comment]
It works after I signed in. I did not expect this to be an issue because I was signed in to GitHub in Safari. Looks like you can’t do something about this as not sharing cookies is an iOS thing.
