### ISSUE TITLE
Can not submit issue in action extension with multiple images

### ISSUE THREAD

**Issue by funkenstrahlen** [cocreation/gitshot#9]
<hr /><div align="center"><img alt="Screenshot uploaded with GitShot" src="https://i.imgur.com/k5Uuj70.png" width="300.0" height="533.6" align="center" /><br><br>Documented with <a href="https://goo.gl/oZUi2a">GitShot</a></div><hr />

There is no way to hide the keyboard or scroll down to find the submit button.

**Comment by jeanfw** [comment]
Reproduced, thanks for reporting this. Will look into it ASAP.

**Comment by jeanfw** [comment]
`v1.2.1` has been submitted to the App Store for review, with this bug fixed. Hopefully it doesn't take too long for them to approve. Thanks again for reporting !
